/* Generated by remotion.sh's sync_all() from <work>/scenes/components/ every time it runs —
   never hand edit. See _registry.ts's own header for why this checked-in copy stays empty. */
import type {FC} from 'react';

export const BESPOKE_COMPONENTS: Record<string, FC<any>> = {};
