/* Generated by remotion.sh's sync_all() from <work>/scenes/ every time it runs — never hand
   edit, never read this file to learn the shape of a bespoke scene (read scenes/QUOTE.ts
   instead, the contract is identical). This checked-in copy is permanently empty: it exists
   only so the template still type-checks in isolation (CI's own template-only `npm run
   check`, with no <work> and no real sync ever run against it — see scenes/index.ts). A real
   project's sync always overwrites this file before anything reads it. */
export const BESPOKE_DEFS = {};
