/* Scenes: the motion graphics drawn over (or instead of) the video. A segment's `scene` chooses
   one — {type: KEYWORD, params: {...}, timing} — and lives exactly as long as that segment.

   Two catalogs, resolved as one. SCENES below is the small, permanent, shared set — reusable
   utility widgets (a checklist, a counter, a stamp) for a plain informational moment that
   genuinely doesn't need its own idea. BESPOKE_SCENES (../bespoke/_registry.ts, generated by
   remotion.sh's sync_all() from a real project's own <work>/scenes/) is that project's own,
   invented fresh for its own sentences — SKILL.md step 10's default path, not a fallback.
   `resolveScene`/`parseScene` below try the shared set first, the project's own second; the
   two can never collide (remotion.sh's sync refuses a bespoke keyword that matches a shared
   one before this file is ever type-checked). A bespoke scene has the exact same two-file
   shape, same `scene()`/param DSL, same component contract as a shared one — the only
   difference is where it's authored.

   Each scene has two files. The definition, named after its keyword (CHECKLIST.ts), says what it
   does, when to use it and which parameters it takes — pure TypeScript, so it loads under plain
   Node for validation. The component (components/Checklist.tsx) draws it; components.tsx pairs
   the two and the type checker refuses a keyword without a component or the reverse.
   Adding a SHARED scene means adding both files and one line in each list; a BESPOKE one needs
   no registration at all — remotion.sh discovers it by filename.

   MAX_SCENELESS_RUN caps how long the video may go with no scene running at all: enforced
   here, not left as prose a scene-design pass could silently under-deliver on. A plan that
   goes quiet too long fails `options/check.ts`, naming the stretch.

   THE COMPONENT CONTRACT. SceneList.tsx renders each active scene with these props:
     t          absolute seconds
     prog       0..1, linear progress through the whole scene (for its own phases)
     dur        the scene's own length in seconds (sc.e - sc.s) — prog*dur is elapsed seconds,
                for a phase that must stay short (a shock, a flash) regardless of how long the
                segment itself runs, instead of stretching to fill it
     enter      0..1, raw linear progress of the entrance (ease it however you like)
     exit       0..1, raw linear progress of the exit (1 = gone)
     words      the sentence's words with their timings: {t, s, e, hot}[]
     wordIndex  how many of those words have started, minus one (-1 before the first)
     itemReveal for a scene whose `items` param is a list, the absolute second each one first
                appeared, parallel to `items` (render_data.py's item_reveal_times) — a segment
                that continued an already-running list inherited its earlier items' real,
                original times, so `t - itemReveal[i]` animates only whichever item is
                actually new; every earlier one is already past its own entrance and reads as
                settled. `undefined`/no `items` param: nothing to key off, animate however
                the scene otherwise would.
     rect       the video card's rectangle at this instant — for an `overlay: true` scene
                (SUSPENSE), which draws ON the video; everything else draws in `area`
     area       the active LAYOUT's own scene rectangle (frame px) — draw inside it, in ITS
                own coordinate space (areaX(k) = area.x + k*area.w, and so on; util.tsx has
                the helper), never in absolute design pixels. A layout can be any size (SPLIT's
                graphic band, FULL's overlay strip, HIDDEN's whole frame): a scene that draws
                relative to `area` renders correctly in every one of them, unchanged.
     theme      the project's colours and font — never hardcode a colour
     params     the scene's parameters, every default applied
   Font sizes, radii and shadows stay literal — that is about how big things read, not where
   they sit. A scene that cannot draw returns null. */
import {defineDomain, distance, locate} from '../options/domain.ts';
import type {Env, Spec} from '../options/domain.ts';
import {EASINGS} from '../transitions/index.ts';
import {BESPOKE_DEFS} from '../bespoke/_registry.ts';
import {CARD_STACK} from './CARD_STACK.ts';
import {CHECKLIST} from './CHECKLIST.ts';
import {COMMENT_BOX} from './COMMENT_BOX.ts';
import {COUNTER} from './COUNTER.ts';
import {FILE_MERGE} from './FILE_MERGE.ts';
import {IMAGE_CARD} from './IMAGE_CARD.ts';
import {QUOTE} from './QUOTE.ts';
import {STAMP} from './STAMP.ts';
import {SUSPENSE} from './SUSPENSE.ts';
import {SYNC_VIZ} from './SYNC_VIZ.ts';
import {TRANSCRIPT_PANEL} from './TRANSCRIPT_PANEL.ts';

// No stretch of the video may go this long without a scene: the visual variety this whole
// domain exists for, not a frame that is merely filled. Generous enough for a natural hook
// (no scene is ever expected in the first few seconds) plus a sentence or two after it —
// long stretches past that are a content gap, not a deliberate quiet moment.
const MAX_SCENELESS_RUN = 12;

/* Every stretch of the video with no scene running, in order — used only to word the audit
   below; a plan with no scenes at all is one giant gap, from 0 to its own end. */
function scenelessGaps(plan: any): string[] {
  const total = typeof plan.total === 'number' ? plan.total : 0;
  if (total <= 0) return [];
  const scenes = [...(plan.scenes ?? [])].sort((a: any, b: any) => a.s - b.s);
  const gaps: string[] = [];
  let cursor = 0;
  const flag = (from: number, to: number) => {
    if (to - from > MAX_SCENELESS_RUN)
      gaps.push(`${from.toFixed(1)}s-${to.toFixed(1)}s: ${(to - from).toFixed(1)}s with no scene — `
        + `over the ${MAX_SCENELESS_RUN}s limit`);
  };
  for (const sc of scenes) { flag(cursor, sc.s); cursor = Math.max(cursor, sc.e); }
  flag(cursor, total);
  return gaps;
}

/* `timing` tunes how a scene enters and leaves: {in, out}, each a number of seconds or
   {duration, easing, y}. */
function timingProblems(timing: any, where: string): string[] {
  if (timing == null) return [];
  const out: string[] = [];
  const mustBe = (what: string) => `${where}: scene timing.${what}`;
  for (const [key, v] of Object.entries<any>(timing)) {
    if (key !== 'in' && key !== 'out') { out.push(`${where}: scene timing has an unknown key "${key}" (keys: in · out)`); continue; }
    if (typeof v === 'number') { if (!(v > 0)) out.push(`${mustBe(key)} must be above 0 seconds`); continue; }
    if (typeof v !== 'object' || v === null) { out.push(`${mustBe(key)} must be a number of seconds or {duration, easing, y}`); continue; }
    for (const [k, x] of Object.entries<any>(v)) {
      if (k === 'duration') { if (!(typeof x === 'number' && x > 0)) out.push(`${mustBe(key)}.duration must be above 0 seconds`); }
      else if (k === 'easing') out.push(...EASINGS.problems(x, mustBe(key) + '.easing'));
      else if (k === 'y') { if (typeof x !== 'number') out.push(`${mustBe(key)}.y must be a number of pixels`); }
      else out.push(`${mustBe(key)} has an unknown key "${k}" (keys: duration · easing · y)`);
    }
  }
  return out;
}

// The project's own scenes (empty in the template itself — see bespoke/_registry.ts's own
// header). No audit of its own: SCENES.audit below already checks every plan.scenes entry
// through `resolveScene`, shared or bespoke alike, and scenelessGaps() reads plan.scenes'
// raw {s,e} regardless of which catalog a scene's type resolved against.
export const BESPOKE_SCENES = defineDomain('scene', BESPOKE_DEFS);

/* Tries the shared catalog first, the project's own bespoke one second. Both `resolve()`
   calls are pure and cheap, so trying both and keeping whichever found something is simpler
   than re-deriving domain.ts's own private keyword-extraction logic here. */
function resolveScene(spec: Spec | null | undefined) {
  const shared = SCENES.resolve(spec);
  if (shared.option || !BESPOKE_SCENES.names.length) return shared;
  const bespoke = BESPOKE_SCENES.resolve(spec);
  if (bespoke.option) return bespoke;
  const word = shared.name, all = [...SCENES.names, ...BESPOKE_SCENES.names];
  const near = word && all.find(n => distance(n, word) <= 2);
  return {name: word, option: undefined, params: {} as Record<string, any>, errors: [word === undefined
    ? `a scene is required (choices: ${all.join(' · ')})`
    : `unknown scene "${word}"${near ? ` - did you mean ${near}?` : ''} (choices: ${all.join(' · ')})`]};
}

/** SceneList.tsx's own entry point — the same contract as SCENES.parse: throws with every
    problem, resolved against the shared catalog and the project's own bespoke one together. */
export function parseScene(spec: Spec | null | undefined) {
  const r = resolveScene(spec);
  if (r.errors.length) throw new Error(r.errors.map(e => `scene ${e}`).join('\n'));
  return {name: r.name, option: r.option!, params: r.params};
}

export const SCENES = defineDomain(
  'scene',
  {CARD_STACK, CHECKLIST, COMMENT_BOX, COUNTER, FILE_MERGE, IMAGE_CARD, QUOTE, STAMP, SUSPENSE, SYNC_VIZ, TRANSCRIPT_PANEL},
  {
    audit: (plan, env: Env) => [
      ...(plan.scenes ?? []).flatMap((sc: any) => {
        const where = locate(sc);
        const spec = {type: sc.type, ...(sc.params ?? {})};
        const r = resolveScene(spec);
        const world = r.errors.length ? [] : ((r.option as any).check?.(r.params, env) ?? []).map((e: string) => `${where}: scene ${e}`);
        return [...r.errors.map(e => `${where}: scene ${e}`), ...world, ...timingProblems(sc.timing, where)];
      }),
      ...scenelessGaps(plan),
    ],
  },
);
