# -*- coding: utf-8 -*-
import sys as _sys
try:
    _sys.stdout.reconfigure(encoding="utf-8"); _sys.stderr.reconfigure(encoding="utf-8")
except Exception:
    pass
"""Copies <work>/scenes/ into the just-synced Remotion project and generates the two barrel
files scenes/index.ts and SceneList.tsx import it through, so a project's own bespoke scenes
(SKILL.md step 10 - invented fresh for this video, never the shared catalog copied verbatim)
type-check and render exactly like a shared one.

    uv run scripts/remotion/sync_bespoke.py <work> <remotion-dir> <template-dir>

Runs from remotion.sh's sync_all(), right after the shared option-domain folders are copied in
and before options/check.ts runs, so a bad bespoke scene is caught there too, not halfway
through a render. <remotion-dir>/src/ was already wiped and rebuilt from the template by the
caller (remotion.sh) before this script ever runs, so there is no stale bespoke/ from a
previous sync to clean up here - only to create fresh.

A project with no <work>/scenes/ at all is the common case and is unaffected: this script
still runs, finds nothing to copy, and writes the same two permanently-empty barrel files the
template itself ships (scripts/remotion/template/src/bespoke/_registry.{ts,tsx}) - so every
existing project renders exactly as it did before this script existed.
"""
import os
import re
import shutil
import sys

KEYWORD = re.compile(r"^[A-Z][A-Z0-9_]*$")


def main(argv):
    if len(argv) < 4:
        sys.exit("usage: sync_bespoke.py <work> <remotion-dir> <template-dir>")
    work = os.path.abspath(argv[1])
    remotion_dir = os.path.abspath(argv[2])
    template_dir = os.path.abspath(argv[3])

    besp = os.path.join(remotion_dir, "src", "bespoke")
    comp = os.path.join(besp, "components")
    os.makedirs(comp, exist_ok=True)

    work_scenes = os.path.join(work, "scenes")
    if os.path.isdir(work_scenes):
        for name in os.listdir(work_scenes):
            src = os.path.join(work_scenes, name)
            if os.path.isfile(src) and name.endswith(".ts"):
                shutil.copy(src, os.path.join(besp, name))
        work_comp = os.path.join(work_scenes, "components")
        if os.path.isdir(work_comp):
            for name in os.listdir(work_comp):
                src = os.path.join(work_comp, name)
                if os.path.isfile(src) and name.endswith(".tsx"):
                    shutil.copy(src, os.path.join(comp, name))

    shared = {fn[:-3] for fn in os.listdir(os.path.join(template_dir, "src", "scenes"))
              if fn.endswith(".ts") and KEYWORD.match(fn[:-3])}

    bespoke = []
    for fn in sorted(os.listdir(besp)):
        if fn == "components" or not fn.endswith(".ts"):
            continue
        stem = fn[:-3]
        if not KEYWORD.match(stem):
            sys.exit("[X] <work>/scenes/%s.ts - a bespoke scene's filename must be an "
                      "UPPERCASE keyword (A-Z, 0-9, _), the same as the shared catalog's own"
                      % stem)
        if stem in shared:
            sys.exit("[X] <work>/scenes/%s.ts - %r is already a shared scene "
                      "(scripts/remotion/template/src/scenes/) - choose a different name "
                      "for this project's own one" % (stem, stem))
        if not os.path.isfile(os.path.join(comp, stem + ".tsx")):
            sys.exit("[X] <work>/scenes/%s.ts has no matching "
                      "<work>/scenes/components/%s.tsx" % (stem, stem))
        bespoke.append(stem)

    with open(os.path.join(besp, "_registry.ts"), "w", encoding="utf-8") as f:
        f.write("/* Generated by remotion.sh's sync_all() from <work>/scenes/ every sync - "
                 "never hand edit, it is overwritten the next time you run remotion.sh. */\n")
        for k in bespoke:
            f.write("import {%s} from './%s.ts';\n" % (k, k))
        f.write("export const BESPOKE_DEFS = {%s};\n" % ", ".join(bespoke))

    with open(os.path.join(besp, "_registry.tsx"), "w", encoding="utf-8") as f:
        f.write("/* Generated by remotion.sh's sync_all() from <work>/scenes/components/ - "
                 "never hand edit. */\n")
        f.write("import type {FC} from 'react';\n")
        for k in bespoke:
            f.write("import %s from './components/%s.tsx';\n" % (k, k))
        f.write("export const BESPOKE_COMPONENTS: Record<string, FC<any>> = {%s};\n"
                 % ", ".join("%s: %s" % (k, k) for k in bespoke))

    if bespoke:
        print("bespoke scenes: " + ", ".join(bespoke))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
